//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source top.tlv 30

//_\SV
   // Included URL: "https://raw.githubusercontent.com/efabless/chipcraft---mest-course/main/tlv_lib/calculator_shell_lib.tlv"
   // Include Tiny Tapeout Lab.
   // Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlv_lib/tiny_tapeout_lib.tlv"// Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlv_lib/fpga_includes.tlv"
//_\source top.tlv 213

//_\SV

// ================================================
// A simple Makerchip Verilog test bench driving random stimulus.
// Modify the module contents to your needs.
// ================================================

module top(input logic clk, input logic reset, input logic [31:0] cyc_cnt, output logic passed, output logic failed);
   // Tiny tapeout I/O signals.
   logic [7:0] ui_in, uo_out;
   logic [7:0]uio_in,  uio_out, uio_oe;
   logic [31:0] r;
   always @(posedge clk) r <= 0;
   assign ui_in = 8'b10000000;
   assign uio_in = 8'b0;
   logic ena = 1'b0;
   logic rst_n = ! reset;

   // Instantiate the Tiny Tapeout module.
   my_design tt(.*);

   assign passed = top.cyc_cnt > 60;
   assign failed = 1'b0;
endmodule


// Provide a wrapper module to debounce input signals if requested.
// The Tiny Tapeout top-level module.
// This simply debounces and synchronizes inputs.
// Debouncing is based on a counter. A change to any input will only be recognized once ALL inputs
// are stable for a certain duration. This approach uses a single counter vs. a counter for each
// bit.
module tt_um_example (
    input  wire [7:0] ui_in,    // Dedicated inputs - connected to the input switches
    output wire [7:0] uo_out,   // Dedicated outputs - connected to the 7 segment display
       // The FPGA is based on TinyTapeout 3 which has no bidirectional I/Os (vs. TT6 for the ASIC).
    input  wire [7:0] uio_in,   // IOs: Bidirectional Input path
    output wire [7:0] uio_out,  // IOs: Bidirectional Output path
    output wire [7:0] uio_oe,   // IOs: Bidirectional Enable path (active high: 0=input, 1=output)
    
    input  wire       ena,      // will go high when the design is enabled
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);
    
    // Synchronize.
    logic [17:0] inputs_ff, inputs_sync;
    always @(posedge clk) begin
        inputs_ff <= {ui_in, uio_in, ena, rst_n};
        inputs_sync <= inputs_ff;
    end

    // Debounce.
    `define DEBOUNCE_MAX_CNT 14'h3fff
    logic [17:0] inputs_candidate, inputs_captured;
    logic sync_rst_n = inputs_sync[0];
    logic [13:0] cnt;
    always @(posedge clk) begin
        if (!sync_rst_n)
           cnt <= `DEBOUNCE_MAX_CNT;
        else if (inputs_sync != inputs_candidate) begin
           // Inputs changed before stablizing.
           cnt <= `DEBOUNCE_MAX_CNT;
           inputs_candidate <= inputs_sync;
        end
        else if (cnt > 0)
           cnt <= cnt - 14'b1;
        else begin
           // Cnt == 0. Capture candidate inputs.
           inputs_captured <= inputs_candidate;
        end
    end
    logic [7:0] clean_ui_in, clean_uio_in;
    logic clean_ena, clean_rst_n;
    assign {clean_ui_in, clean_uio_in, clean_ena, clean_rst_n} = inputs_captured;

    my_design my_design (
        .ui_in(clean_ui_in),
        .uio_in(clean_uio_in),
        .ena(clean_ena),
        .rst_n(clean_rst_n),
        .*);
endmodule
//_\SV



// =======================
// The Tiny Tapeout module
// =======================

module my_design (
    input  wire [7:0] ui_in,    // Dedicated inputs - connected to the input switches
    output wire [7:0] uo_out,   // Dedicated outputs - connected to the 7 segment display
       // The FPGA is based on TinyTapeout 3 which has no bidirectional I/Os (vs. TT6 for the ASIC).
    input  wire [7:0] uio_in,   // IOs: Bidirectional Input path
    output wire [7:0] uio_out,  // IOs: Bidirectional Output path
    output wire [7:0] uio_oe,   // IOs: Bidirectional Enable path (active high: 0=input, 1=output)
    
    input  wire       ena,      // will go high when the design is enabled
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);
   wire reset = ! rst_n;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /usr/local/mono/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar digit, exp, input_label, leds, sbox_k, sbox_subword, sub_word, switch, xx, yy;


//
// Signals declared top-level.
//

// For $slideswitch.
logic [7:0] L0_slideswitch_a0;

// For $sseg_decimal_point_n.
logic L0_sseg_decimal_point_n_a0;

// For $sseg_digit_n.
logic [7:0] L0_sseg_digit_n_a0;

// For $sseg_segment_n.
logic [6:0] L0_sseg_segment_n_a0;

// For /fpga_pins/fpga|encrypt$blk_counter.
logic [22:0] FpgaPins_Fpga_ENCRYPT_blk_counter_a0,
             FpgaPins_Fpga_ENCRYPT_blk_counter_a1;

// For /fpga_pins/fpga|encrypt$blocks_to_run.
logic [22:0] FpgaPins_Fpga_ENCRYPT_blocks_to_run_a0;

// For /fpga_pins/fpga|encrypt$ld_init.
logic FpgaPins_Fpga_ENCRYPT_ld_init_a0,
      FpgaPins_Fpga_ENCRYPT_ld_init_a1;

// For /fpga_pins/fpga|encrypt$ld_key.
logic FpgaPins_Fpga_ENCRYPT_ld_key_a0,
      FpgaPins_Fpga_ENCRYPT_ld_key_a1;

// For /fpga_pins/fpga|encrypt$ofb.
logic FpgaPins_Fpga_ENCRYPT_ofb_a0;

// For /fpga_pins/fpga|encrypt$r_counter.
logic [4:0] FpgaPins_Fpga_ENCRYPT_r_counter_a0,
            FpgaPins_Fpga_ENCRYPT_r_counter_a1;

// For /fpga_pins/fpga|encrypt$reset.
logic FpgaPins_Fpga_ENCRYPT_reset_a0,
      FpgaPins_Fpga_ENCRYPT_reset_a1;

// For /fpga_pins/fpga|encrypt$run_key.
logic FpgaPins_Fpga_ENCRYPT_run_key_a0,
      FpgaPins_Fpga_ENCRYPT_run_key_a1;

// For /fpga_pins/fpga|encrypt$sbox_vec.
logic [2047:0] FpgaPins_Fpga_ENCRYPT_sbox_vec_a0;

// For /fpga_pins/fpga|encrypt$start_key.
logic [127:0] FpgaPins_Fpga_ENCRYPT_start_key_a0;

// For /fpga_pins/fpga|encrypt$state_ark.
logic [127:0] FpgaPins_Fpga_ENCRYPT_state_ark_a0,
              FpgaPins_Fpga_ENCRYPT_state_ark_a1;

// For /fpga_pins/fpga|encrypt$state_i.
logic [127:0] FpgaPins_Fpga_ENCRYPT_state_i_a0,
              FpgaPins_Fpga_ENCRYPT_state_i_a1;

// For /fpga_pins/fpga|encrypt$state_mc.
logic [127:0] FpgaPins_Fpga_ENCRYPT_state_mc_a0;

// For /fpga_pins/fpga|encrypt$state_ssr.
logic [127:0] FpgaPins_Fpga_ENCRYPT_state_ssr_a0;

// For /fpga_pins/fpga|encrypt$test_state.
logic [127:0] FpgaPins_Fpga_ENCRYPT_test_state_a0;

// For /fpga_pins/fpga|encrypt$ui_in.
logic [7:0] FpgaPins_Fpga_ENCRYPT_ui_in_a0;

// For /fpga_pins/fpga|encrypt$valid.
logic FpgaPins_Fpga_ENCRYPT_valid_a0;

// For /fpga_pins/fpga|encrypt$valid_blk.
logic FpgaPins_Fpga_ENCRYPT_valid_blk_a0;

// For /fpga_pins/fpga|encrypt$valid_check.
logic FpgaPins_Fpga_ENCRYPT_valid_check_a0;

// For /fpga_pins/fpga|encrypt/check$pass.
logic [0:0] FpgaPins_Fpga_ENCRYPT_Check_pass_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$g0_run_key.
logic FpgaPins_Fpga_ENCRYPT_Keyschedule_g0_run_key_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$key.
logic [127:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$next_key.
logic [127:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a0,
              FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a1;

// For /fpga_pins/fpga|encrypt/keyschedule$next_worda.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_next_worda_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$next_wordb.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordb_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$next_wordc.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordc_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$next_wordd.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordd_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$rcon.
logic [7:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a0,
            FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a1;

// For /fpga_pins/fpga|encrypt/keyschedule$rot.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_rot_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$run_key.
logic FpgaPins_Fpga_ENCRYPT_Keyschedule_run_key_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$sb_out.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_sb_out_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$temp.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_temp_a0;

// For /fpga_pins/fpga|encrypt/keyschedule$xor_con.
logic [31:0] FpgaPins_Fpga_ENCRYPT_Keyschedule_xor_con_a0;

// For /fpga_pins/fpga|encrypt/mixcolumn$block_out.
logic [127:0] FpgaPins_Fpga_ENCRYPT_Mixcolumn_block_out_a0;

// For /fpga_pins/fpga|encrypt/mixcolumn$const_matrix.
logic [127:0] FpgaPins_Fpga_ENCRYPT_Mixcolumn_const_matrix_a0;

// For /fpga_pins/fpga|encrypt/mixcolumn/xx/yy$cc.
logic [7:0] FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0 [3:0][3:0];

// For /fpga_pins/fpga|encrypt/mixcolumn/xx/yy$ss.
logic [7:0] FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0 [3:0][3:0];

// For /fpga_pins/fpga|encrypt/subbytes$ssr_out.
logic [127:0] FpgaPins_Fpga_ENCRYPT_Subbytes_ssr_out_a0;




   //
   // Scope: /fpga_pins
   //


      //
      // Scope: /fpga
      //


         //
         // Scope: |encrypt
         //

            // Staging of $blk_counter.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_blk_counter_a1[22:0] <= FpgaPins_Fpga_ENCRYPT_blk_counter_a0[22:0];

            // Staging of $ld_init.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_ld_init_a1 <= FpgaPins_Fpga_ENCRYPT_ld_init_a0;

            // Staging of $ld_key.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_ld_key_a1 <= FpgaPins_Fpga_ENCRYPT_ld_key_a0;

            // Staging of $r_counter.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_r_counter_a1[4:0] <= FpgaPins_Fpga_ENCRYPT_r_counter_a0[4:0];

            // Staging of $reset.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_reset_a1 <= FpgaPins_Fpga_ENCRYPT_reset_a0;

            // Staging of $run_key.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_run_key_a1 <= FpgaPins_Fpga_ENCRYPT_run_key_a0;

            // Staging of $state_ark.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_state_ark_a1[127:0] <= FpgaPins_Fpga_ENCRYPT_state_ark_a0[127:0];

            // Staging of $state_i.
            always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_state_i_a1[127:0] <= FpgaPins_Fpga_ENCRYPT_state_i_a0[127:0];


            //
            // Scope: /keyschedule
            //

               // Staging of an unconditioned version of a condition signal.
               assign FpgaPins_Fpga_ENCRYPT_Keyschedule_g0_run_key_a0 = FpgaPins_Fpga_ENCRYPT_Keyschedule_run_key_a0 && FpgaPins_Fpga_ENCRYPT_valid_blk_a0;

               // Staging of $next_key.
               always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a1[127:0] <= FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a0[127:0];

               // Staging of $rcon.
               always_ff @(posedge clk) FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a1[7:0] <= FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a0[7:0];









//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS_GTKWAVE

      (* keep *) logic [7:0] \@0$slideswitch ;
      assign \@0$slideswitch = L0_slideswitch_a0;
      (* keep *) logic  \@0$sseg_decimal_point_n ;
      assign \@0$sseg_decimal_point_n = L0_sseg_decimal_point_n_a0;
      (* keep *) logic [7:0] \@0$sseg_digit_n ;
      assign \@0$sseg_digit_n = L0_sseg_digit_n_a0;
      (* keep *) logic [6:0] \@0$sseg_segment_n ;
      assign \@0$sseg_segment_n = L0_sseg_segment_n_a0;

      //
      // Scope: /digit[0:0]
      //
      for (digit = 0; digit <= 0; digit++) begin : \/digit 

         //
         // Scope: /leds[7:0]
         //
         for (leds = 0; leds <= 7; leds++) begin : \/leds 
            (* keep *) logic  \//@0$viz_lit ;
            assign \//@0$viz_lit = L1_Digit[digit].L2_Leds[leds].L2_viz_lit_a0;
         end
      end

      //
      // Scope: /fpga_pins
      //
      if (1) begin : \/fpga_pins 

         //
         // Scope: /fpga
         //
         if (1) begin : \/fpga 

            //
            // Scope: |encrypt
            //
            if (1) begin : P_encrypt
               (* keep *) logic [22:0] \///@0$blk_counter ;
               assign \///@0$blk_counter = FpgaPins_Fpga_ENCRYPT_blk_counter_a0;
               (* keep *) logic [22:0] \///@0$blocks_to_run ;
               assign \///@0$blocks_to_run = FpgaPins_Fpga_ENCRYPT_blocks_to_run_a0;
               (* keep *) logic  \///?$valid_blk@0$ld_init ;
               assign \///?$valid_blk@0$ld_init = FpgaPins_Fpga_ENCRYPT_ld_init_a0;
               (* keep *) logic  \///?$valid_blk@0$ld_key ;
               assign \///?$valid_blk@0$ld_key = FpgaPins_Fpga_ENCRYPT_ld_key_a0;
               (* keep *) logic  \///@0$ofb ;
               assign \///@0$ofb = FpgaPins_Fpga_ENCRYPT_ofb_a0;
               (* keep *) logic [4:0] \///?$valid_blk@0$r_counter ;
               assign \///?$valid_blk@0$r_counter = FpgaPins_Fpga_ENCRYPT_r_counter_a0;
               (* keep *) logic  \///@0$reset ;
               assign \///@0$reset = FpgaPins_Fpga_ENCRYPT_reset_a0;
               (* keep *) logic  \///?$valid_blk@0$run_key ;
               assign \///?$valid_blk@0$run_key = FpgaPins_Fpga_ENCRYPT_run_key_a0;
               (* keep *) logic [2047:0] \///@0$sbox_vec ;
               assign \///@0$sbox_vec = FpgaPins_Fpga_ENCRYPT_sbox_vec_a0;
               (* keep *) logic [127:0] \///@0$start_key ;
               assign \///@0$start_key = FpgaPins_Fpga_ENCRYPT_start_key_a0;
               (* keep *) logic [127:0] \///?$valid_blk@0$state_ark ;
               assign \///?$valid_blk@0$state_ark = FpgaPins_Fpga_ENCRYPT_state_ark_a0;
               (* keep *) logic [127:0] \///?$valid_blk@0$state_i ;
               assign \///?$valid_blk@0$state_i = FpgaPins_Fpga_ENCRYPT_state_i_a0;
               (* keep *) logic [127:0] \///?$valid_blk@0$state_mc ;
               assign \///?$valid_blk@0$state_mc = FpgaPins_Fpga_ENCRYPT_state_mc_a0;
               (* keep *) logic [127:0] \///?$valid_blk@0$state_ssr ;
               assign \///?$valid_blk@0$state_ssr = FpgaPins_Fpga_ENCRYPT_state_ssr_a0;
               (* keep *) logic [127:0] \///@0$test_state ;
               assign \///@0$test_state = FpgaPins_Fpga_ENCRYPT_test_state_a0;
               (* keep *) logic [7:0] \///@0$ui_in ;
               assign \///@0$ui_in = FpgaPins_Fpga_ENCRYPT_ui_in_a0;
               (* keep *) logic  \///@0$valid ;
               assign \///@0$valid = FpgaPins_Fpga_ENCRYPT_valid_a0;
               (* keep *) logic  \///@0$valid_blk ;
               assign \///@0$valid_blk = FpgaPins_Fpga_ENCRYPT_valid_blk_a0;
               (* keep *) logic  \///@0$valid_check ;
               assign \///@0$valid_check = FpgaPins_Fpga_ENCRYPT_valid_check_a0;

               //
               // Scope: /check
               //
               if (1) begin : \/check 
                  (* keep *) logic [0:0] \///?$valid_check/@0$pass ;
                  assign \///?$valid_check/@0$pass = FpgaPins_Fpga_ENCRYPT_Check_pass_a0;
               end

               //
               // Scope: /keyschedule
               //
               if (1) begin : \/keyschedule 
                  (* keep *) logic [127:0] \///?$valid_blk/@0$key ;
                  assign \///?$valid_blk/@0$key = FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0;
                  (* keep *) logic [127:0] \///?$valid_blk/@0$next_key ;
                  assign \///?$valid_blk/@0$next_key = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$next_worda ;
                  assign \///?$valid_blk/?$run_key@0$next_worda = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_worda_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$next_wordb ;
                  assign \///?$valid_blk/?$run_key@0$next_wordb = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordb_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$next_wordc ;
                  assign \///?$valid_blk/?$run_key@0$next_wordc = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordc_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$next_wordd ;
                  assign \///?$valid_blk/?$run_key@0$next_wordd = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordd_a0;
                  (* keep *) logic [7:0] \///?$valid_blk/?$run_key@0$rcon ;
                  assign \///?$valid_blk/?$run_key@0$rcon = FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$rot ;
                  assign \///?$valid_blk/?$run_key@0$rot = FpgaPins_Fpga_ENCRYPT_Keyschedule_rot_a0;
                  (* keep *) logic  \///?$valid_blk/@0$run_key ;
                  assign \///?$valid_blk/@0$run_key = FpgaPins_Fpga_ENCRYPT_Keyschedule_run_key_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$sb_out ;
                  assign \///?$valid_blk/?$run_key@0$sb_out = FpgaPins_Fpga_ENCRYPT_Keyschedule_sb_out_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$temp ;
                  assign \///?$valid_blk/?$run_key@0$temp = FpgaPins_Fpga_ENCRYPT_Keyschedule_temp_a0;
                  (* keep *) logic [31:0] \///?$valid_blk/?$run_key@0$xor_con ;
                  assign \///?$valid_blk/?$run_key@0$xor_con = FpgaPins_Fpga_ENCRYPT_Keyschedule_xor_con_a0;

                  //
                  // Scope: /sbox_k[3:0]
                  //
                  for (sbox_k = 0; sbox_k <= 3; sbox_k++) begin : \/sbox_k 
                     (* keep *) logic [10:0] \///?$valid_blk/?$run_key/@0$sb_idx ;
                     assign \///?$valid_blk/?$run_key/@0$sb_idx = L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[sbox_k].L1_sb_idx_a0;
                     (* keep *) logic [7:0] \///?$valid_blk/?$run_key/@0$sb_intermed ;
                     assign \///?$valid_blk/?$run_key/@0$sb_intermed = L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[sbox_k].L1_sb_intermed_a0;
                     (* keep *) logic [7:0] \///?$valid_blk/?$run_key/@0$word_idx ;
                     assign \///?$valid_blk/?$run_key/@0$word_idx = L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[sbox_k].L1_word_idx_a0;
                  end
               end

               //
               // Scope: /mixcolumn
               //
               if (1) begin : \/mixcolumn 
                  (* keep *) logic [127:0] \///?$valid_blk/@0$block_out ;
                  assign \///?$valid_blk/@0$block_out = FpgaPins_Fpga_ENCRYPT_Mixcolumn_block_out_a0;
                  (* keep *) logic [127:0] \///?$valid_blk/@0$const_matrix ;
                  assign \///?$valid_blk/@0$const_matrix = FpgaPins_Fpga_ENCRYPT_Mixcolumn_const_matrix_a0;

                  //
                  // Scope: /xx[3:0]
                  //
                  for (xx = 0; xx <= 3; xx++) begin : \/xx 
                     (* keep *) logic [31:0] \///?$valid_blk//@0$out_matrix ;
                     assign \///?$valid_blk//@0$out_matrix = L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[xx].L1_out_matrix_a0;

                     //
                     // Scope: /yy[3:0]
                     //
                     for (yy = 0; yy <= 3; yy++) begin : \/yy 
                        (* keep *) logic [7:0] \///?$valid_blk///@0$cc ;
                        assign \///?$valid_blk///@0$cc = FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0[xx][yy];
                        (* keep *) logic [7:0] \///?$valid_blk///@0$oo ;
                        assign \///?$valid_blk///@0$oo = L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[xx].L2_Yy[yy].L2_oo_a0;
                        (* keep *) logic [7:0] \///?$valid_blk///@0$ss ;
                        assign \///?$valid_blk///@0$ss = FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][yy];

                        //
                        // Scope: /exp[3:0]
                        //
                        for (exp = 0; exp <= 3; exp++) begin : \/exp 
                           (* keep *) logic [7:0] \///?$valid_blk////@0$op ;
                           assign \///?$valid_blk////@0$op = L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[xx].L2_Yy[yy].L3_Exp[exp].L3_op_a0;
                           (* keep *) logic [7:0] \///?$valid_blk////@0$reduce_check ;
                           assign \///?$valid_blk////@0$reduce_check = L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[xx].L2_Yy[yy].L3_Exp[exp].L3_reduce_check_a0;
                           (* keep *) logic [7:0] \///?$valid_blk////@0$three_check ;
                           assign \///?$valid_blk////@0$three_check = L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[xx].L2_Yy[yy].L3_Exp[exp].L3_three_check_a0;
                        end
                     end
                  end
               end

               //
               // Scope: /subbytes
               //
               if (1) begin : \/subbytes 
                  (* keep *) logic [127:0] \///?$valid_blk/@0$ssr_out ;
                  assign \///?$valid_blk/@0$ssr_out = FpgaPins_Fpga_ENCRYPT_Subbytes_ssr_out_a0;

                  //
                  // Scope: /sub_word[3:0]
                  //
                  for (sub_word = 0; sub_word <= 3; sub_word++) begin : \/sub_word 
                     (* keep *) logic [31:0] \///?$valid_blk//@0$sb_out ;
                     assign \///?$valid_blk//@0$sb_out = L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[sub_word].L1_sb_out_a0;
                     (* keep *) logic [31:0] \///?$valid_blk//@0$word ;
                     assign \///?$valid_blk//@0$word = L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[sub_word].L1_word_a0;

                     //
                     // Scope: /sbox_subword[3:0]
                     //
                     for (sbox_subword = 0; sbox_subword <= 3; sbox_subword++) begin : \/sbox_subword 
                        (* keep *) logic [10:0] \///?$valid_blk///@0$sb_idx ;
                        assign \///?$valid_blk///@0$sb_idx = L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[sub_word].L2_SboxSubword[sbox_subword].L2_sb_idx_a0;
                        (* keep *) logic [7:0] \///?$valid_blk///@0$sb_intermed ;
                        assign \///?$valid_blk///@0$sb_intermed = L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[sub_word].L2_SboxSubword[sbox_subword].L2_sb_intermed_a0;
                        (* keep *) logic [7:0] \///?$valid_blk///@0$word_idx ;
                        assign \///?$valid_blk///@0$word_idx = L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[sub_word].L2_SboxSubword[sbox_subword].L2_word_idx_a0;
                     end
                  end
               end
            end
         end
      end

      //
      // Scope: /switch[7:0]
      //
      for (switch = 0; switch <= 7; switch++) begin : \/switch 
         (* keep *) logic  \/@0$viz_switch ;
         assign \/@0$viz_switch = L1_Switch[switch].L1_viz_switch_a0;
      end


   end

// ---------- Generated Code Ends ----------
//_\TLV
   /* verilator lint_off UNOPTFLAT */
   // Connect Tiny Tapeout I/Os to Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 76   // Instantiated from top.tlv, 268 as: m5+tt_connections()
      assign L0_slideswitch_a0[7:0] = ui_in;
      assign L0_sseg_segment_n_a0[6:0] = ~ uo_out[6:0];
      assign L0_sseg_decimal_point_n_a0 = ~ uo_out[7];
      assign L0_sseg_digit_n_a0[7:0] = 8'b11111110;
   //_\end_source

   // Instantiate the Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 307   // Instantiated from top.tlv, 271 as: m5+board(/top, /fpga, 7, $, , calc)
      
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 355   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 309 as: m4+thanks(m5__l(309)m5_eval(m5_get(BOARD_THANKS_ARGS)))
         //_/thanks
            
      //_\end_source
      
   
      // Board VIZ.
   
      // Board Image.
      
      //_/fpga_pins
         
         //_/fpga
            //_\source top.tlv 134   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 340 as: m4+calc.
               //_|encrypt
                  //_@0
                     assign FpgaPins_Fpga_ENCRYPT_sbox_vec_a0[2047:0] = 2048'h637c777bf26b6fc5_3001672bfed7ab76_ca82c97dfa5947f0_add4a2af9ca472c0_b7fd9326363ff7cc3_4a5e5f171d8311504_c723c31896059a07_1280e2eb27b27509_832c1a1b6e5aa052_3bd6b329e32f8453d_100ed20fcb15b6ac_bbe394a4c58cfd0e_faafb434d338545f9_027f503c9fa851a34_08f929d38f5bcb6da2_110fff3d2cd0c13e_c5f974417c4a77e3_d645d197360814fd_c222a908846eeb814_de5e0bdbe0323a0a_4906245cc2d3ac629_195e479e7c8376d8d_d54ea96c56f4ea65_7aae08ba78252e1c_a6b4c6e8dd741f4b_bd8b8a703eb56648_03f60e613557b986_c11d9ee1f8981169_d98e949b1e87e9ce_5528df8ca1890dbfe_6426841992d0fb05_4bb16;
                     //
                     //
            
                     assign FpgaPins_Fpga_ENCRYPT_ui_in_a0[7:0] = ui_in;   //Input to determine mode/keys
                     assign FpgaPins_Fpga_ENCRYPT_ofb_a0 = FpgaPins_Fpga_ENCRYPT_ui_in_a0[7];             //Switch to determine mode
                     assign FpgaPins_Fpga_ENCRYPT_blocks_to_run_a0[22:0] = 2000000;     //Blocks of AES to run if in OFB
            
                     //Initial State or IV
                     assign FpgaPins_Fpga_ENCRYPT_test_state_a0[127:0] =  128'h00000000000000000000000000000000;
            
                     //Initial Key
                     assign FpgaPins_Fpga_ENCRYPT_start_key_a0[127:0] =  FpgaPins_Fpga_ENCRYPT_ui_in_a0[0] ? 128'hffff_ffff_ffff_80000000000000000000 :
                                          FpgaPins_Fpga_ENCRYPT_ui_in_a0[1] ? 128'hffffffffffffc0000000000000000000 :
                                          FpgaPins_Fpga_ENCRYPT_ui_in_a0[2] ? 128'hffffffffffffe0000000000000000000 :
                                          FpgaPins_Fpga_ENCRYPT_ui_in_a0[3] ? 128'hfffffffffffff0000000000000000000 :
                                          128'hfffffffffffff8000000000000000000;
            
                     assign FpgaPins_Fpga_ENCRYPT_valid_blk_a0 = (FpgaPins_Fpga_ENCRYPT_ofb_a0 && (FpgaPins_Fpga_ENCRYPT_blk_counter_a0 <= FpgaPins_Fpga_ENCRYPT_blocks_to_run_a0)) || !FpgaPins_Fpga_ENCRYPT_ofb_a0;
                     //Counter to count the number of AES blocks performed
                     assign FpgaPins_Fpga_ENCRYPT_blk_counter_a0[22:0] = !FpgaPins_Fpga_ENCRYPT_reset_a0 && FpgaPins_Fpga_ENCRYPT_reset_a1 ? 0 :
                                          !FpgaPins_Fpga_ENCRYPT_ld_key_a0 && FpgaPins_Fpga_ENCRYPT_ld_key_a1 ? FpgaPins_Fpga_ENCRYPT_blk_counter_a1+1 :
                                          FpgaPins_Fpga_ENCRYPT_blk_counter_a1;
            
                     //Reset if *reset or if the ofb_count reaches 12 when in OFB
                     assign FpgaPins_Fpga_ENCRYPT_reset_a0 = reset;
                     assign FpgaPins_Fpga_ENCRYPT_valid_check_a0 = FpgaPins_Fpga_ENCRYPT_valid_a0 && !FpgaPins_Fpga_ENCRYPT_ofb_a0;
                     assign FpgaPins_Fpga_ENCRYPT_valid_a0 = FpgaPins_Fpga_ENCRYPT_r_counter_a0==11;
                     //_?$valid_blk
            
            
                        //If in ECB, this checks to see if the AES block if completed
            
            
                        assign FpgaPins_Fpga_ENCRYPT_ld_key_a0 = ((!FpgaPins_Fpga_ENCRYPT_reset_a0 && FpgaPins_Fpga_ENCRYPT_reset_a1) || FpgaPins_Fpga_ENCRYPT_r_counter_a1 == 10) ? 1 : 0;
            
                        assign FpgaPins_Fpga_ENCRYPT_run_key_a0 = (!FpgaPins_Fpga_ENCRYPT_ld_key_a0 && FpgaPins_Fpga_ENCRYPT_ld_key_a1) ? 1 :
                                   (FpgaPins_Fpga_ENCRYPT_run_key_a1 && FpgaPins_Fpga_ENCRYPT_ofb_a0 && FpgaPins_Fpga_ENCRYPT_blk_counter_a1 <= FpgaPins_Fpga_ENCRYPT_blocks_to_run_a0 ) ? 1 :
                                   (!FpgaPins_Fpga_ENCRYPT_ofb_a0 && FpgaPins_Fpga_ENCRYPT_r_counter_a1 < 11) ? 1 :
                                   0;
            
                        assign FpgaPins_Fpga_ENCRYPT_ld_init_a0 = !FpgaPins_Fpga_ENCRYPT_reset_a0 && FpgaPins_Fpga_ENCRYPT_reset_a1 ? 1 : 0;
                        //round counter
                        assign FpgaPins_Fpga_ENCRYPT_r_counter_a0[4:0] = FpgaPins_Fpga_ENCRYPT_reset_a0 ? 0 :
                                          !FpgaPins_Fpga_ENCRYPT_ld_key_a0 && FpgaPins_Fpga_ENCRYPT_ld_key_a1 ? 0 :
                                          (FpgaPins_Fpga_ENCRYPT_ofb_a0 && FpgaPins_Fpga_ENCRYPT_r_counter_a1 > 10) ? 0 :
                                          FpgaPins_Fpga_ENCRYPT_run_key_a0 ? FpgaPins_Fpga_ENCRYPT_r_counter_a1+1 :
                                          FpgaPins_Fpga_ENCRYPT_r_counter_a1;
            
                        //Perform the key schedule subroutine
                        //_\source top.tlv 105   // Instantiated from top.tlv, 187 as: m5+keyschedule(|encrypt, /keyschedule, $start_key, $run_key, $reset, $r_counter, $ld_key)
                           //_/keyschedule
                        
                              //KEY is the exposed output to main. The current key to use will be displayed.
                              //After ARK is done on main, it should pulse the keyschedule which will cause
                              //it to calculate the next key and have it ready for use.
                              assign FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[127:0] = FpgaPins_Fpga_ENCRYPT_reset_a0 ?  '0 : //resets key (loads dummy for testing)
                                            FpgaPins_Fpga_ENCRYPT_ld_key_a0 ? FpgaPins_Fpga_ENCRYPT_start_key_a0 :  //pulls in initial key
                                            FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a1; //loads next key
                        
                              assign FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a0[127:0] = FpgaPins_Fpga_ENCRYPT_ld_key_a0 ? FpgaPins_Fpga_ENCRYPT_start_key_a0 : //full key for next clock
                                                 FpgaPins_Fpga_ENCRYPT_run_key_a0 ? {FpgaPins_Fpga_ENCRYPT_Keyschedule_next_worda_a0, FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordb_a0, FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordc_a0, FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordd_a0} :
                                                 FpgaPins_Fpga_ENCRYPT_Keyschedule_next_key_a1;
                              assign FpgaPins_Fpga_ENCRYPT_Keyschedule_run_key_a0 = FpgaPins_Fpga_ENCRYPT_run_key_a0;
                              //_?$run_key
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_temp_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[31:0];                //w[i+3]
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_rot_a0[31:0] = {FpgaPins_Fpga_ENCRYPT_Keyschedule_temp_a0[23:0],FpgaPins_Fpga_ENCRYPT_Keyschedule_temp_a0[31:24]}; // rotate word
                        
                                 //_\source top.tlv 53   // Instantiated from top.tlv, 123 as: m5+sbox(/keyschedule, /sbox_k, $rot)
                                    for (sbox_k = 0; sbox_k <= 3; sbox_k++) begin : L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK //_/sbox_k

                                       // For $sb_idx.
                                       logic [10:0] L1_sb_idx_a0;

                                       // For $sb_intermed.
                                       logic [7:0] L1_sb_intermed_a0;

                                       // For $word_idx.
                                       logic [7:0] L1_word_idx_a0;

                                 
                                       assign L1_sb_idx_a0[10:0] = 2040-8*L1_word_idx_a0;
                                       assign L1_word_idx_a0[7:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_rot_a0[32-(8 * (sbox_k+1)) +: 8];
                                       assign L1_sb_intermed_a0[7:0] = FpgaPins_Fpga_ENCRYPT_sbox_vec_a0[L1_sb_idx_a0 +: 8];
                                    end
                                    assign FpgaPins_Fpga_ENCRYPT_Keyschedule_sb_out_a0[31:0] = {L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[0].L1_sb_intermed_a0, L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[1].L1_sb_intermed_a0, L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[2].L1_sb_intermed_a0, L1_FpgaPins_Fpga_ENCRYPT_Keyschedule_SboxK[3].L1_sb_intermed_a0};
                                 //_\end_source
                        
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a0[7:0] = FpgaPins_Fpga_ENCRYPT_r_counter_a0 == 0 ? 8'h01 : //round constant
                                              FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a1 <  8'h80 ? (2 * FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a1) :
                                                         ((2 * FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a1) ^ 8'h1B);
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_xor_con_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_sb_out_a0[31:0] ^ {FpgaPins_Fpga_ENCRYPT_Keyschedule_rcon_a0, 24'b0}; // xor with the round constant
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_next_worda_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_xor_con_a0 ^ FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[127:96];  // ripple solve for next words
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordb_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_worda_a0 ^ FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[95:64];
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordc_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordb_a0 ^ FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[63:32];
                                 assign FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordd_a0[31:0] = FpgaPins_Fpga_ENCRYPT_Keyschedule_next_wordc_a0 ^ FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0[31:0];
                        //_\end_source
                        //set the initial state
                        assign FpgaPins_Fpga_ENCRYPT_state_i_a0[127:0] = FpgaPins_Fpga_ENCRYPT_reset_a0 ? '0:
                                          !FpgaPins_Fpga_ENCRYPT_ld_init_a0 && FpgaPins_Fpga_ENCRYPT_ld_init_a1 ? FpgaPins_Fpga_ENCRYPT_test_state_a0 :
                                          (FpgaPins_Fpga_ENCRYPT_run_key_a0 && FpgaPins_Fpga_ENCRYPT_r_counter_a1<11) ? FpgaPins_Fpga_ENCRYPT_state_ark_a1 :
                                          FpgaPins_Fpga_ENCRYPT_state_i_a1;
            
                        //Perform the subbytes and shift row subroutines
                        //_\source top.tlv 42   // Instantiated from top.tlv, 195 as: m5+subbytes(|encrypt, /subbytes, $state_i)
                           //_/subbytes
                              for (sub_word = 0; sub_word <= 3; sub_word++) begin : L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord //_/sub_word

                                 // For $sb_out.
                                 logic [31:0] L1_sb_out_a0;

                                 // For $word.
                                 logic [31:0] L1_word_a0;

                                 assign L1_word_a0[31:0] = FpgaPins_Fpga_ENCRYPT_state_i_a0[128-(32*(sub_word+1))+:32];
                                 //_\source top.tlv 53   // Instantiated from top.tlv, 46 as: m5+sbox(/sub_word, /sbox_subword, $word)
                                    for (sbox_subword = 0; sbox_subword <= 3; sbox_subword++) begin : L2_SboxSubword //_/sbox_subword

                                       // For $sb_idx.
                                       logic [10:0] L2_sb_idx_a0;

                                       // For $sb_intermed.
                                       logic [7:0] L2_sb_intermed_a0;

                                       // For $word_idx.
                                       logic [7:0] L2_word_idx_a0;

                                 
                                       assign L2_sb_idx_a0[10:0] = 2040-8*L2_word_idx_a0;
                                       assign L2_word_idx_a0[7:0] = L1_word_a0[32-(8 * (sbox_subword+1)) +: 8];
                                       assign L2_sb_intermed_a0[7:0] = FpgaPins_Fpga_ENCRYPT_sbox_vec_a0[L2_sb_idx_a0 +: 8];
                                    end
                                    assign L1_sb_out_a0[31:0] = {L2_SboxSubword[0].L2_sb_intermed_a0, L2_SboxSubword[1].L2_sb_intermed_a0, L2_SboxSubword[2].L2_sb_intermed_a0, L2_SboxSubword[3].L2_sb_intermed_a0};
                                 //_\end_source
                              end
                        
                              assign FpgaPins_Fpga_ENCRYPT_Subbytes_ssr_out_a0[127:0] = {L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[0].L1_sb_out_a0[31:24], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[1].L1_sb_out_a0[23:16], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[2].L1_sb_out_a0[15:8], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[3].L1_sb_out_a0[7:0],
                                                 L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[1].L1_sb_out_a0[31:24], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[2].L1_sb_out_a0[23:16], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[3].L1_sb_out_a0[15:8], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[0].L1_sb_out_a0[7:0],
                                                 L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[2].L1_sb_out_a0[31:24], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[3].L1_sb_out_a0[23:16], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[0].L1_sb_out_a0[15:8], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[1].L1_sb_out_a0[7:0],
                                                 L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[3].L1_sb_out_a0[31:24], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[0].L1_sb_out_a0[23:16], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[1].L1_sb_out_a0[15:8], L1_FpgaPins_Fpga_ENCRYPT_Subbytes_SubWord[2].L1_sb_out_a0[7:0]};
                        //_\end_source
                        assign FpgaPins_Fpga_ENCRYPT_state_ssr_a0[127:0] = FpgaPins_Fpga_ENCRYPT_r_counter_a0 ==0 ? FpgaPins_Fpga_ENCRYPT_state_i_a0 : FpgaPins_Fpga_ENCRYPT_Subbytes_ssr_out_a0;
            
                        //Perform the mixcolumn subroutine
                        //_\source top.tlv 79   // Instantiated from top.tlv, 199 as: m5+mixcolumn(|encrypt, /mixcolumn, $state_ssr)
                           //_/mixcolumn
                        
                              assign FpgaPins_Fpga_ENCRYPT_Mixcolumn_const_matrix_a0[127:0] = 128'h02030101010203010101020303010102; //constant matrix for column multiplicaiton in the form of a vector
                              for (xx = 0; xx <= 3; xx++) begin : L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx //_/xx

                                 // For $out_matrix.
                                 logic [31:0] L1_out_matrix_a0;

                                 for (yy = 0; yy <= 3; yy++) begin : L2_Yy //_/yy

                                    // For $oo.
                                    logic [7:0] L2_oo_a0;

                                    assign FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][yy][7:0] = FpgaPins_Fpga_ENCRYPT_state_ssr_a0[(yy * 8 + xx * 32) + 7 : (yy * 8 + xx * 32)];     //breaks the input vector and
                                    assign FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0[xx][yy][7:0] = FpgaPins_Fpga_ENCRYPT_Mixcolumn_const_matrix_a0[(yy * 32 + xx * 8) + 7 : (yy * 32 + xx * 8)]; //constant matrix into matrices
                                    for (exp = 0; exp <= 3; exp++) begin : L3_Exp //_/exp

                                       // For $op.
                                       logic [7:0] L3_op_a0;

                                       // For $reduce_check.
                                       logic [7:0] L3_reduce_check_a0;

                                       // For $three_check.
                                       logic [7:0] L3_three_check_a0;

                        
                                       assign L3_reduce_check_a0[7:0] = (FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][exp][7] == 1) && (FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0[exp][yy] != 8'h01) ? 8'h1b : 8'h00; //check if a reduction by the irreducibly polynomial is necessary
                                       assign L3_three_check_a0[7:0] = FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0[exp][yy] == 8'h03 ? FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][exp] : 8'h00; //check if a multiplication by 3 is being done
                                       assign L3_op_a0[7:0] = FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_cc_a0[exp][yy] == 8'h01 ? FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][exp] : ((FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx_Yy_ss_a0[xx][exp] << 1) ^ L3_three_check_a0 ^ L3_reduce_check_a0); //if 1, identity. otherwise, bitshift & other operations.
                                    end
                                    assign L2_oo_a0[7:0] = L3_Exp[0].L3_op_a0 ^ L3_Exp[1].L3_op_a0 ^ L3_Exp[2].L3_op_a0 ^ L3_Exp[3].L3_op_a0; //xor the bytes together
                                    
                                 end
                                 assign L1_out_matrix_a0[31:0] = {L2_Yy[3].L2_oo_a0, L2_Yy[2].L2_oo_a0, L2_Yy[1].L2_oo_a0, L2_Yy[0].L2_oo_a0} ; //concat matrix rows
                              end
                              assign FpgaPins_Fpga_ENCRYPT_Mixcolumn_block_out_a0[127:0] = {L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[3].L1_out_matrix_a0, L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[2].L1_out_matrix_a0, L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[1].L1_out_matrix_a0, L1_FpgaPins_Fpga_ENCRYPT_Mixcolumn_Xx[0].L1_out_matrix_a0}; //concat matrix columns
                        //_\end_source
                        assign FpgaPins_Fpga_ENCRYPT_state_mc_a0[127:0] = (FpgaPins_Fpga_ENCRYPT_r_counter_a0 ==0 || FpgaPins_Fpga_ENCRYPT_r_counter_a0 == 10) ? FpgaPins_Fpga_ENCRYPT_state_ssr_a0 : FpgaPins_Fpga_ENCRYPT_Mixcolumn_block_out_a0;
            
                        //Perform the add round key subroutine
                        assign FpgaPins_Fpga_ENCRYPT_state_ark_a0[127:0] = FpgaPins_Fpga_ENCRYPT_state_mc_a0 ^ FpgaPins_Fpga_ENCRYPT_Keyschedule_key_a0;
            
                        //If in ECB, check for a correct encryption
            
                     //_?$valid_check
                        //_\source top.tlv 63   // Instantiated from top.tlv, 208 as: m5+check(|encrypt, /check, $state_i, $ui_in)
                        
                           //_/check
                        
                              assign FpgaPins_Fpga_ENCRYPT_Check_pass_a0[0:0] = FpgaPins_Fpga_ENCRYPT_ui_in_a0 == 1 ? (FpgaPins_Fpga_ENCRYPT_state_i_a0 == 128'hb6768473ce9843ea66a81405dd50b345) :
                                           FpgaPins_Fpga_ENCRYPT_ui_in_a0 == 2 ? (FpgaPins_Fpga_ENCRYPT_state_i_a0 == 128'hcb2f430383f9084e03a653571e065de6) :
                                           FpgaPins_Fpga_ENCRYPT_ui_in_a0 == 4 ? (FpgaPins_Fpga_ENCRYPT_state_i_a0 == 128'hff4e66c07bae3e79fb7d210847a3b0ba) :
                                           FpgaPins_Fpga_ENCRYPT_ui_in_a0 == 8 ? (FpgaPins_Fpga_ENCRYPT_state_i_a0 == 128'h7b90785125505fad59b13c186dd66ce3) :
                                           (FpgaPins_Fpga_ENCRYPT_state_i_a0 == 128'h8b527a6aebdaec9eaef8eda2cb7783e5);
                        
                              assign uo_out = FpgaPins_Fpga_ENCRYPT_Check_pass_a0 ? 8'b00111111 :
                                        8'b01110110;
                        //_\end_source
            
               // Connect Tiny Tapeout outputs. Note that uio_ outputs are not available in the Tiny-Tapeout-3-based FPGA boards.
               //*uo_out = 8'b0;
               assign uio_out = 8'b0;
               assign uio_oe = 8'b0;
            //_\end_source
   
      // LEDs.
      
   
      // 7-Segment
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 395   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 346 as: m4+fpga_sseg.
         for (digit = 0; digit <= 0; digit++) begin : L1_Digit //_/digit
            
            for (leds = 0; leds <= 7; leds++) begin : L2_Leds //_/leds

               // For $viz_lit.
               logic L2_viz_lit_a0;

               assign L2_viz_lit_a0 = (! L0_sseg_digit_n_a0[digit]) && ! ((leds == 7) ? L0_sseg_decimal_point_n_a0 : L0_sseg_segment_n_a0[leds % 7]);
               
            end
         end
      //_\end_source
   
      // slideswitches
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 454   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 349 as: m4+fpga_switch.
         for (switch = 0; switch <= 7; switch++) begin : L1_Switch //_/switch

            // For $viz_switch.
            logic L1_viz_switch_a0;

            assign L1_viz_switch_a0 = L0_slideswitch_a0[switch];
            
         end
      //_\end_source
   
      // pushbuttons
      
   //_\end_source
   // Label the switch inputs [0..7] (1..8 on the physical switch panel) (top-to-bottom).
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 82   // Instantiated from top.tlv, 273 as: m5+tt_input_labels_viz(⌈"Value[0]", "Value[1]", "Value[2]", "Value[3]", "Op[0]", "Op[1]", "Op[2]", "="⌉)
      for (input_label = 0; input_label <= 7; input_label++) begin : L1_InputLabel //_/input_label
         
      end
   //_\end_source

//_\SV
endmodule



// Undefine macros defined by SandPiper.
`undef BOGUS_USE
